name: Read Hello File

on:
  push:
    branches:
      - main

jobs:
  read-file-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read and output hello.txt content
        run: |
          echo "📄 Content of hello.txt:"
          cat hello.txt
